version: '{build}'

image: Visual Studio 2019

configuration: Debug

platform: x86

before_build:

- ps: nuget restore src\Puzzle.sln

build:

  project: src/Puzzle.sln

  verbosity: minimal

test_script:

- cmd: C:\projects\puzzlegame15\src\Debug\Test.exe